### ISSUE TITLE
Have you released KeyCastOW on the Microsoft Store?

### ISSUE THREAD

**Issue by AJpon** [brookhong/KeyCastOW#23]

**Comment by AJpon** [comment]
This application is registered and sold in the store under your name.

* [KeyCastOW - Download and install on Windows | Microsoft Store](https://apps.microsoft.com/detail/9nwztztb05pg?ocid=pdpshare)

![image](https://github.com/user-attachments/assets/2d530520-08c2-490f-a553-972e183293df)


The code in this repository has a copywrite of 2015, but the store version is 2024.
However, there is no evidence in this repository that such a change has been made.

![](https://store-images.s-microsoft.com/image/apps.40516.14435631442999359.61020829-86ee-4c82-b977-8856d9be2358.5a1653f3-f424-4517-ad49-c240dd0f80ef)

Did you submit this app?
I would gladly buy this app if it was submitted by you,
I can't determine that since there are no updates in this repository.

Even if it's not you, it's MIT licensed, so you can use it commercially.

However, it is not a good idea for someone else to use your name for commercial purposes.

I would appreciate a reply.

**Comment by AJpon** [comment]
I didn't know there was a link to your site, thanks for sharing! I'll definitely buy it!
* [KeyCastOW -- keycast on windows](https://brookhong.github.io/2014/04/28/keycast-on-windows.html)

**Comment by brookhong** [comment]
Yes, that is me, thanks for asking.
