### ISSUE TITLE
Binary Releases

### ISSUE THREAD

**Issue by X-Raym** [brookhong/KeyCastOW#5]
Hi,
Nice software !

Seems solid enough to provide binary install as GitHub releases now :)

Will make sharing easier than having to create our own .exe.

Thanks for your consideration !

**Comment by AlesRFK** [comment]
So how can I run this?
MSBUILD : error MSB1008: Only one project can be specified. Dont get it :/

**Comment by NathanLovato** [comment]
I second this: May you consider adding a release? https://github.com/brookhong/KeyCastOW/releases
It's okay if you'd rather not provide support or anything but it'd make your program accessible to more people.

**Comment by brookhong** [comment]
Guys, binary release was there, but somehow was reported as malware to several antivirus softwares, and even caused my github page site marked as malicious one.

I have to remove it, and no more binary provided.

https://github.com/brookhong/brookhong.github.io/blob/master/assets/downloads/keycastow.zip

Here is where it was. It should still be accessible from github.

Build command is 

    msbuild /p:platform=win32 /p:Configuration=Release

**Comment by X-Raym** [comment]
@brookhong it is usual for antivirus to flag unknown and unsigned .exe as virus, but the more users will uses it, the more it will be analysed by various antivirus, and then they may become more tolerant.
Thats why providing releases .exe in a accessible way (on a custom FTP or cmoud service if GitHub releases are blocked) would really help.
Also if you find other problems, you can contact GitHub support directly, or move to GitLab.

I cant tell to my little brother or my grandma "If you want to use it, just dowbload 11 Gb of Virtual Studio and run this command line" :P

Thanks for your support !
